### ISSUE TITLE
Intégration: Positionnement du FileManager avec un Dashboard

### ISSUE THREAD

**Issue by moudarir** [Grafikart/FileManagerJS#9]
Salut,

Il y a un soucis de positionnement du FileManager lorsqu'on l'intègre avec un Dashboard existant.
![Capture d’écran 2022-04-10 à 22 22 14](https://user-images.githubusercontent.com/12732173/162642520-7d584d32-2438-47a0-83f3-898559fc4723.png)

Ça marche si je désactive le `position: fixed;` dans la class `fm-overlay`
![Capture d’écran 2022-04-10 à 22 33 53](https://user-images.githubusercontent.com/12732173/162642630-50566cc4-350d-4a25-91ed-c404544a9a29.png)

**Comment by Grafikart** [comment]
Tu peux appliquer du CSS directement sur `<file-manager>` pour mettre un z-index supérieur à celui de ton dashboard ?

**Comment by moudarir** [comment]
Effectivement, un `z-index` supérieur avec `position:relative;` solutionne le problème.

Merci.
